### ISSUE TITLE
Not able to import add-on repository

### ISSUE THREAD

**Issue by panayiotism** [samueltardieu/homeassistant-addon-pi-cec#10]
Hi, and thanks for your contribution.
I'm fairly new to homeassistant, when trying to import your repository to homeassistant add-ons I'm getting the error:
**https://github.com/samueltardieu/homeassistant-addon-pi-cec is not a valid add-on repository**

I'm running the latest version of homeassistant 2022.11.3 on a Raspberry Pi 3

**Comment by hshelby** [comment]
I made the same mistake. You're using the wrong URL for the add-on repository. You need to use https://github.com/samueltardieu/homeassistant-addons .

**Comment by samueltardieu** [comment]
Thanks @hshelby. I've added a note in the README about this.
