### ISSUE TITLE
Can someone tell me how to install

### ISSUE THREAD

**Issue by ghost** [samueltardieu/homeassistant-addon-pi-cec#14]
I cannot figure out how to install pi-cec. It says add repository but I am not seeing how to do this. Do I add repository to HA or to docker? I try to build the dockerfile but this doesn't work as it says build from cant be blank. Do I need HA installed in a docker, do I need HA core installed, or do I need HA Supervised installed?

Can someone point me in the right direction as I a missing the obvious

**Comment by samueltardieu** [comment]
You need to add "https://github.com/samueltardieu/homeassistant-addons" as a repository in your "addons" configuration section of HA.

Note that I don't use Rasperry Pi for HA anymore (I switched to a more powerful machine) so I can't offer any support.

**Comment by ghost** [comment]
Thanks for the help. From what I have read, you need HA Supervised in order to have an addons section and you can't do this with an HA docker image. Do I need to do this under HA Supervised?

I see you have a dockerfile so I am not sure how best to install this/

**Comment by samueltardieu** [comment]
As far as I know, you're right, addons are only available under HA supervised. I don't know how you can proceed with HA in a docker.

**Comment by ghost** [comment]
Okay, I was able to install HA supervised in Arch and it uses a docker so I was able to install pi-cec. I get an error about not being able to open /dev/vchqi. I dont have this device on my rpi5 in arch aarch64
