### ISSUE TITLE
RPI4 - assertion failure in vc_vchi_dispmanx_init() - and fix

### ISSUE THREAD

**Issue by barneyman** [samueltardieu/homeassistant-addon-pi-cec#6]
Running this on my RPI4 returned the following error

`2022-04-11 11:16:41,060 - pycec - WARNING - Be aware! Network is using shared event loop!
assertion failure:/home/buildozer/aports/main/raspberrypi/src/userland-f73fca015d421b763936667a0b58fe5024d59921/interface/vmcs_host/vc_vchi_dispmanx.c:201:vc_vchi_dispmanx_init():success == 0`

This was fixed by increasing GPU memory from 16M to 128M - other values may work

**Comment by samueltardieu** [comment]
Thanks for the fix.
